name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.9.0

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'

    - name: Install Dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Install Dependencies Browsers
      run:
        - sudo apt-get update
        - sudo apt-get install -y libsoup2.4-1 libwoff2dec1 libvpx6 libevent-2.1-7 libopus0 libharfbuzz-icu0 libgstreamer-plugins-base1.0-0 libflite1 libx264-152 libgles2

    - name: Run Playwright tests
      run: npm test

    - name: Generate Allure report
      run: npm run generate-allure-report
      continue-on-error: true

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: playwright-report/
        retention-days: 30

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: report